import os
import json
import time
import zipfile
import shutil
import pandas as pd
import torch
from datasets import Dataset
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainerCallback
from peft import LoraConfig, get_peft_model
from trl import SFTTrainer, SFTConfig

def create_export_package(output_dir: str, package_name: str, files_to_zip: list, metadata: dict, metrics: dict) -> str:
    """Creates a self-describing zip package."""
    os.makedirs(output_dir, exist_ok=True)
    
    with open(os.path.join(output_dir, "metadata.json"), "w") as f:
        json.dump(metadata, f, indent=2)
        
    with open(os.path.join(output_dir, "metrics.json"), "w") as f:
        json.dump(metrics, f, indent=2)
        
    with open(os.path.join(output_dir, "README.md"), "w") as f:
        f.write(f"# {metadata.get('task_type', 'Export')}\n\nGenerated by iLoveLLM.")
        
    files_to_zip.extend([
        os.path.join(output_dir, "metadata.json"),
        os.path.join(output_dir, "metrics.json"),
        os.path.join(output_dir, "README.md")
    ])
    
    zip_path = os.path.join(output_dir, package_name)
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for fpath in files_to_zip:
            if os.path.isdir(fpath):
                for root, _, files in os.walk(fpath):
                    for file in files:
                        full_path = os.path.join(root, file)
                        arcname = os.path.relpath(full_path, output_dir)
                        zipf.write(full_path, arcname)
            else:
                arcname = os.path.basename(fpath)
                zipf.write(fpath, arcname)
                
    return zip_path

class HeartbeatCallback(TrainerCallback):
    def __init__(self, heartbeat_fn):
        self.heartbeat_fn = heartbeat_fn
        self.last_heartbeat = time.time()
        
    def on_step_end(self, args, state, control, **kwargs):
        if time.time() - self.last_heartbeat > 30:
            if self.heartbeat_fn:
                self.heartbeat_fn()
            self.last_heartbeat = time.time()

def prepare_dataset(file_path: str, input_col: str, output_col: str, target_format: str = 'chatml'):
    ext = os.path.splitext(file_path)[1].lower()
    if ext == ".csv":
        df = pd.read_csv(file_path)
    elif ext in [".json", ".jsonl"]:
        df = pd.read_json(file_path, lines=(ext==".jsonl"))
    else:
        raise ValueError("Only CSV and JSONL files are supported.")

    df = df.dropna(subset=[input_col, output_col])
    formatted_texts = []
    
    for _, row in df.iterrows():
        user_text = str(row[input_col])
        assistant_text = str(row[output_col])
        formatted = f"<|im_start|>user\n{user_text}<|im_end|>\n<|im_start|>assistant\n{assistant_text}<|im_end|>"
        formatted_texts.append(formatted)
        
    return Dataset.from_dict({"text": formatted_texts})

def execute_lora_sft(dataset, output_dir, heartbeat_fn=None, batch_size=1, lr=2e-4, epochs=1, lora_rank=8):
    model_id = "Qwen/Qwen2.5-0.5B" # lightweight model
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(model_id, device_map="cpu", torch_dtype=torch.float32)
    peft_config = LoraConfig(r=lora_rank, lora_alpha=lora_rank * 2, target_modules=["q_proj", "v_proj"], task_type="CAUSAL_LM")
    model = get_peft_model(model, peft_config)
    model.train()

    # Enforce strict budget and steps
    training_args = SFTConfig(
        output_dir=output_dir,
        per_device_train_batch_size=batch_size,
        gradient_accumulation_steps=4,
        learning_rate=lr,
        num_train_epochs=epochs,
        logging_steps=10,
        save_strategy="steps",
        save_steps=50,
        max_steps=200, # Hard limit budget
        use_cpu=True,
        dataset_text_field="text",
        max_length=512,
    )

    trainer = SFTTrainer(
        model=model,
        train_dataset=dataset,
        processing_class=tokenizer,
        args=training_args,
        callbacks=[HeartbeatCallback(heartbeat_fn)]
    )

    trainer.train()
    
    adapter_dir = os.path.join(output_dir, "adapter")
    trainer.model.save_pretrained(adapter_dir)
    tokenizer.save_pretrained(adapter_dir)
    
    # Zip package
    metadata = {"task_type": "lora_sft", "model": model_id, "epochs": epochs, "lora_rank": lora_rank}
    metrics = {"final_loss": trainer.state.log_history[-1].get("loss", None) if trainer.state.log_history else None}
    
    zip_path = create_export_package(output_dir, "lora_export.zip", [adapter_dir], metadata, metrics)
    return zip_path, metadata, metrics

def train_small_classifier(dataset_df: pd.DataFrame, input_col: str, output_col: str, output_dir: str, heartbeat_fn=None):
    import pickle
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.linear_model import LogisticRegression
    from sklearn.pipeline import Pipeline
    
    if heartbeat_fn: heartbeat_fn()
    
    pipeline = Pipeline([
        ('tfidf', TfidfVectorizer(max_features=5000, stop_words='english')),
        ('clf', LogisticRegression(max_iter=500))
    ])
    
    df = dataset_df.dropna(subset=[input_col, output_col]).copy()
    X = df[input_col].astype(str)
    y = df[output_col].astype(str)
    
    pipeline.fit(X, y)
    
    if heartbeat_fn: heartbeat_fn()
    
    model_path = os.path.join(output_dir, "model.pkl")
    with open(model_path, "wb") as f:
        pickle.dump(pipeline, f)
        
    metadata = {"task_type": "classifier", "classes": list(pipeline.classes_)}
    metrics = {"accuracy_train_set": pipeline.score(X, y)}
    
    zip_path = create_export_package(output_dir, "classifier_export.zip", [model_path], metadata, metrics)
    return zip_path, metadata, metrics

def train_extractor(dataset_df: pd.DataFrame, input_col: str, output_col: str, output_dir: str, heartbeat_fn=None):
    if heartbeat_fn: heartbeat_fn()
    config_path = os.path.join(output_dir, "extractor_config.json")
    with open(config_path, "w") as f:
        json.dump({"type": "schema_extractor", "target_keys": "auto-detected"}, f)
        
    metadata = {"task_type": "extractor"}
    metrics = {}
    
    zip_path = create_export_package(output_dir, "extractor_export.zip", [config_path], metadata, metrics)
    return zip_path, metadata, metrics

def build_rag_pipeline(dataset_df: pd.DataFrame, input_col: str, output_col: str, output_dir: str, heartbeat_fn=None):
    import chromadb
    if heartbeat_fn: heartbeat_fn()
    db_path = os.path.join(output_dir, "chroma_db")
    client = chromadb.PersistentClient(path=db_path)
    collection = client.create_collection(name="rag_knowledge_base")
    
    df = dataset_df.dropna(subset=[output_col]).copy()
    docs = df[output_col].astype(str).tolist()
    ids = [f"doc_{i}" for i in range(len(docs))]
    
    # Process in batches to heartbeat
    batch_size = 1000
    for i in range(0, len(docs), batch_size):
        collection.add(documents=docs[i:i+batch_size], ids=ids[i:i+batch_size])
        if heartbeat_fn: heartbeat_fn()
        
    metadata = {"task_type": "rag", "documents_indexed": len(docs)}
    metrics = {}
    
    zip_path = create_export_package(output_dir, "rag_export.zip", [db_path], metadata, metrics)
    return zip_path, metadata, metrics
